from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml


ALIAS_RE = re.compile(r"^[a-z][a-z0-9-]{0,31}$")
POLICY_VERSION = "medzen.llm.policy-source.v1"
REQUIRED_RULES = {
    "answer_in_the_requested_language",
    "use_only_the_supplied_citations_for_factual_claims",
    "preserve_the_user_transcript_without_rewriting_it",
    "refuse_when_no_citation_support_is_available",
    "never_emit_patient_or_person_identifiers_to_logs",
}


class PolicyRefusal(RuntimeError):
    """The requested language policy is missing, ambiguous or malformed."""


@dataclass(frozen=True)
class LanguagePolicy:
    language: str
    response_language: str
    policy_id: str
    policy_sha256: str
    engine: str
    citations_required: bool
    maximum_citations: int
    maximum_input_characters: int
    maximum_output_tokens: int
    timeout_ms: int
    rules: tuple[str, ...]


def _canonical(value: Any) -> bytes:
    return json.dumps(
        value, sort_keys=True, separators=(",", ":"), ensure_ascii=False
    ).encode("utf-8")


class PolicyStore:
    def __init__(self, registry_dir: Path, policy_source: Path):
        self.registry_dir = registry_dir.resolve()
        self.policy_source = policy_source.resolve()
        try:
            self.source_raw = self.policy_source.read_bytes()
            self.source = yaml.safe_load(self.source_raw)
        except (OSError, yaml.YAMLError, UnicodeDecodeError) as exc:
            raise PolicyRefusal("language policy source is unreadable") from exc
        if not isinstance(self.source, dict):
            raise PolicyRefusal("language policy source must be an object")
        if set(self.source) != {"version", "classification", "defaults", "policies"}:
            raise PolicyRefusal("language policy source fields are incomplete or unknown")
        if self.source["version"] != POLICY_VERSION:
            raise PolicyRefusal("language policy source version is unsupported")
        if self.source["classification"] != "B6_2_LOCAL_MOCK_ONLY":
            raise PolicyRefusal("language policy source is not local-mock scoped")
        if not isinstance(self.source["defaults"], dict):
            raise PolicyRefusal("language policy defaults are malformed")
        if not isinstance(self.source["policies"], dict) or not self.source["policies"]:
            raise PolicyRefusal("language policies are empty")
        self.source_sha256 = hashlib.sha256(self.source_raw).hexdigest()

    def aliases(self) -> tuple[str, ...]:
        """Serving aliases: every generated record, EXCLUDING data_only
        declarations. A data_only language holds evaluation data and no
        capability (registry A4 rung below 'declared') — the platform
        refuses it at request time rather than manufacturing a policy."""
        serving = []
        for path in sorted(self.registry_dir.glob("*.yaml")):
            if self._is_data_only(path):
                continue
            serving.append(path.stem)
        return tuple(serving)

    @staticmethod
    def _is_data_only(path: Path) -> bool:
        try:
            record = yaml.safe_load(path.read_bytes())
        except (OSError, yaml.YAMLError, UnicodeDecodeError):
            return False  # unreadable files keep failing closed in load()
        return isinstance(record, dict) and record.get("status") == "data_only"

    def validate_all(self) -> dict[str, LanguagePolicy]:
        aliases = self.aliases()
        if not aliases:
            raise PolicyRefusal("generated language registry is empty")
        loaded = {alias: self.load(alias) for alias in aliases}
        referenced = {policy.policy_id for policy in loaded.values()}
        configured = set(self.source["policies"])
        if referenced != configured:
            raise PolicyRefusal("language policy source and registry references differ")
        return loaded

    def load(self, alias: str) -> LanguagePolicy:
        if ALIAS_RE.fullmatch(alias) is None:
            raise PolicyRefusal("language alias is malformed")
        path = self.registry_dir / f"{alias}.yaml"
        if path.is_file() and self._is_data_only(path):
            raise PolicyRefusal(
                "language holds evaluation data only — no serving capability"
            )
        try:
            raw = path.read_bytes()
            language = yaml.safe_load(raw)
        except (OSError, yaml.YAMLError, UnicodeDecodeError) as exc:
            raise PolicyRefusal("generated language record is unreadable") from exc
        if not raw.startswith(b"# GENERATED by scripts/generate_languages.py"):
            raise PolicyRefusal("language record is not generated from its source of truth")
        if not isinstance(language, dict) or language.get("alias") != alias:
            raise PolicyRefusal("generated language identity is ambiguous")
        llm = language.get("llm")
        if not isinstance(llm, dict) or llm.get("engine") != "bedrock":
            raise PolicyRefusal("language LLM engine is unsupported")
        policy_id = llm.get("policy")
        if not isinstance(policy_id, str) or not policy_id:
            raise PolicyRefusal("language policy reference is missing")
        entry = self.source["policies"].get(policy_id)
        if not isinstance(entry, dict) or set(entry) != {"language", "response_language"}:
            raise PolicyRefusal("referenced language policy is missing or malformed")
        if entry["language"] != alias:
            raise PolicyRefusal("language policy reference targets another language")
        if not isinstance(entry["response_language"], str) or not entry["response_language"]:
            raise PolicyRefusal("response language is missing")
        defaults = self.source["defaults"]
        expected = {
            "engine",
            "citations_required",
            "maximum_citations",
            "maximum_input_characters",
            "maximum_output_tokens",
            "timeout_ms",
            "rules",
        }
        if set(defaults) != expected:
            raise PolicyRefusal("language policy defaults are incomplete or unknown")
        rules = defaults["rules"]
        if not isinstance(rules, list) or set(rules) != REQUIRED_RULES:
            raise PolicyRefusal("language policy safety rules differ from v1")
        if defaults["engine"] != "bedrock" or defaults["citations_required"] is not True:
            raise PolicyRefusal("language policy engine or citation gate is unsafe")
        for field, low, high in (
            ("maximum_citations", 1, 5),
            ("maximum_input_characters", 1, 8000),
            ("maximum_output_tokens", 1, 4096),
            ("timeout_ms", 1, 30000),
        ):
            value = defaults[field]
            if isinstance(value, bool) or not isinstance(value, int) or not low <= value <= high:
                raise PolicyRefusal(f"language policy {field} is out of bounds")
        binding = {
            "source_sha256": self.source_sha256,
            "policy_id": policy_id,
            "entry": entry,
            "defaults": defaults,
        }
        return LanguagePolicy(
            language=alias,
            response_language=entry["response_language"],
            policy_id=policy_id,
            policy_sha256=hashlib.sha256(_canonical(binding)).hexdigest(),
            engine=defaults["engine"],
            citations_required=defaults["citations_required"],
            maximum_citations=defaults["maximum_citations"],
            maximum_input_characters=defaults["maximum_input_characters"],
            maximum_output_tokens=defaults["maximum_output_tokens"],
            timeout_ms=defaults["timeout_ms"],
            rules=tuple(rules),
        )
