#!/usr/bin/env python3
"""Render IAM policies and Kubernetes manifests from platform/services.yaml.

Why generate rather than hand-write: A2 defines seven roles and five
deployments with exact probe, resource and GPU settings. Hand-maintaining
fourteen files guarantees drift between the architecture document and the
cluster. Here, services.yaml is the only thing a human edits.

    python platform/generate.py            # write files
    python platform/generate.py --check    # fail if generated output is stale (CI)
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent
IAM_DIR = ROOT / "iam"
K8S_DIR = ROOT / "k8s" / "base"
BANNER = "# GENERATED by platform/generate.py from services.yaml — DO NOT EDIT\n"


# --------------------------------------------------------------------------- #
# IAM
# --------------------------------------------------------------------------- #
def arn_for(perm: dict, meta: dict) -> list[str]:
    """Turn the shorthand in services.yaml into concrete ARNs.

    The bucket ARN is emitted ONLY when s3:ListBucket is requested. Including
    it everywhere makes Deny statements over-broad and object-action grants
    meaningless (PutObject on a bucket ARN is not a thing).
    """
    acct, region = meta["account_id"], meta["region"]
    res, path = perm["resource"], perm.get("path", "*")
    wants_list = "s3:ListBucket" in perm.get("actions", [])

    if res == "data":
        b = meta["buckets"]["data"]
        return [f"arn:aws:s3:::{b}"] if wants_list else [f"arn:aws:s3:::{b}/{path}"]
    if res == "audio_cache":
        b = meta["buckets"]["audio_cache"]
        return [f"arn:aws:s3:::{b}"] if wants_list else [f"arn:aws:s3:::{b}/{path}"]
    if res == "registry":
        return [f"arn:aws:ssm:{region}:{acct}:parameter{meta['registry_ssm_prefix']}/*"]
    if res == "secret":
        return [f"arn:aws:secretsmanager:{region}:{acct}:secret:{perm['name']}*"]
    if res == "ecr":
        # No trailing wildcard: a repository grant must name one repository.
        # "repository/medzen-trainer*" would also match medzen-trainer-anything.
        return [f"arn:aws:ecr:{region}:{acct}:repository/{perm['name']}"]
    if res == "bedrock":
        # the EU cross-region profile FANS OUT to destination-region
        # foundation models — granting only the in-region ARNs made
        # every real invocation fail (Codex serving review finding 7)
        # ALL SIX destinations the eu.* cross-region profile fans out
        # to (Codex serving review round 2: eu-south-1/2 were missing;
        # live sim implicit-denied non-Frankfurt regions)
        destinations = ["eu-central-1", "eu-west-1", "eu-west-3",
                        "eu-north-1", "eu-south-1", "eu-south-2"]
        return ([f"arn:aws:bedrock:{d}::foundation-model/*"
                 for d in destinations]
                + [f"arn:aws:bedrock:{region}:{acct}:inference-profile/eu.*"])
    if res == "*":
        return ["*"]
    raise ValueError(f"unknown resource shorthand: {res}")


def kms_statements(perms: list[dict], meta: dict) -> list[dict]:
    """Derive the SSE-KMS key grants implied by the S3 grants.

    Both buckets use SSE-KMS with customer-managed keys, so an s3:GetObject
    grant is inert without kms:Decrypt and s3:PutObject without
    kms:GenerateDataKey. The resulting AccessDenied names the KMS action, not
    the S3 one, so an S3-only policy review passes while every call fails.

    Derived, not declared: writing these by hand per role is exactly the
    omission that cost three preflight attempts, and it would recur for every
    role added later. A key grant cannot be forgotten if nobody writes it.

    Multipart uploads (checkpoints are large) need Decrypt as well as
    GenerateDataKey, so a write grant implies both.
    """
    keys = meta.get("kms", {})
    need: dict[str, set[str]] = {}
    registry_need: dict[str, set[str]] = {}
    secret_need: dict[str, set[str]] = {}
    for p in perms:
        arn = keys.get(p["resource"])
        if not arn:
            continue                                  # unencrypted or non-S3
        actions = set(p["actions"])
        # B6v2 round 3 (Codex): medzen/speech/fish-api-key is encrypted
        # with the customer-managed key — GetSecretValue without
        # kms:Decrypt fails with a KMS AccessDenied that an S3/secret-only
        # policy review never sees. Same derived-not-declared rule as the
        # bucket grants; scoped to decryption VIA Secrets Manager only.
        if p["resource"] == "secret":
            if "secretsmanager:GetSecretValue" in actions:
                secret_need.setdefault(arn, set()).add("kms:Decrypt")
            continue
        if p["resource"] == "registry":
            if actions & {"ssm:GetParameter", "ssm:GetParameters",
                          "ssm:GetParametersByPath"}:
                registry_need.setdefault(arn, set()).add("kms:Decrypt")
            if "ssm:PutParameter" in actions:
                registry_need.setdefault(arn, set()).update(
                    {"kms:Encrypt", "kms:GenerateDataKey"})
            continue
        if "s3:GetObject" in actions:
            need.setdefault(arn, set()).add("kms:Decrypt")
        if "s3:PutObject" in actions:
            need.setdefault(arn, set()).update({"kms:GenerateDataKey", "kms:Decrypt"})
    statements = [
        {"Sid": f"SseKmsFor{_sid(arn)}", "Effect": "Allow",
         # DescribeKey lets the SDK resolve key state before a transfer;
         # read-only metadata, no data-plane power.
         "Action": sorted(acts | {"kms:DescribeKey"}), "Resource": [arn]}
        for arn, acts in sorted(need.items())
    ]
    for arn, acts in sorted(registry_need.items()):
        statements.extend([
            {"Sid": f"RegistryKmsMetadataFor{_sid(arn)}", "Effect": "Allow",
             "Action": ["kms:DescribeKey"], "Resource": [arn]},
            {"Sid": f"RegistryKmsDataFor{_sid(arn)}", "Effect": "Allow",
             "Action": sorted(acts), "Resource": [arn],
             "Condition": {
                 "StringEquals": {
                     "kms:ViaService": f"ssm.{meta['region']}.amazonaws.com"},
                 "StringLike": {
                     "kms:EncryptionContext:PARAMETER_ARN": (
                         f"arn:aws:ssm:{meta['region']}:{meta['account_id']}:"
                         f"parameter{meta['registry_ssm_prefix']}/*")}}},
        ])
    for arn, acts in sorted(secret_need.items()):
        statements.append(
            {"Sid": f"SecretKmsFor{_sid(arn)}", "Effect": "Allow",
             "Action": sorted(acts), "Resource": [arn],
             "Condition": {
                 "StringEquals": {
                     "kms:ViaService": (
                         f"secretsmanager.{meta['region']}.amazonaws.com")}}})
    return statements                            # sorted inputs => idempotent output


def _sid(key_arn: str) -> str:
    """Stable Sid fragment from a key ARN (Sids allow only alphanumerics)."""
    return key_arn.rsplit("/", 1)[-1].replace("-", "")[:12].title()


def build_policy(perms: list[dict], denies: list[dict], meta: dict) -> dict:
    """Split each permission so object actions and ListBucket get correct ARNs,
    and constrain ListBucket to its prefix with a condition (a resource path
    does not restrict ListBucket — only s3:prefix does)."""
    stmts = []
    for p in perms:
        obj_actions = [a for a in p["actions"] if a != "s3:ListBucket"]
        if obj_actions:
            stmts.append({"Effect": "Allow", "Action": obj_actions,
                          "Resource": arn_for({**p, "actions": obj_actions}, meta)})
        if "s3:ListBucket" in p["actions"]:
            prefix = p.get("path", "*").rstrip("*")
            stmts.append({
                "Effect": "Allow", "Action": ["s3:ListBucket"],
                "Resource": arn_for({**p, "actions": ["s3:ListBucket"]}, meta),
                "Condition": {"StringLike": {"s3:prefix": [f"{prefix}*"]}}})
    stmts.extend(kms_statements(perms, meta))
    for d in denies or []:
        stmts.append({"Effect": "Deny", "Action": d["actions"],
                      "Resource": arn_for(d, meta), "Sid": "".join(
                          c for c in d["why"][:48].title() if c.isalnum())})
    return {"Version": "2012-10-17", "Statement": stmts}


def gen_iam(spec: dict) -> dict[str, str]:
    meta, out = spec["meta"], {}
    everything = (list(spec["services"].items())
                  + list(spec.get("init_containers", {}).items()))
    for name, s in everything:
        pi = s["pod_identity"]
        out[f"{pi['role_name']}.json"] = json.dumps(
            build_policy(pi["permissions"], None, meta), indent=2) + "\n"
    for name, s in spec.get("offline", {}).items():
        out[f"{s['iam_role']}.json"] = json.dumps(
            build_policy(s["permissions"], s.get("explicit_denies"), meta),
            indent=2) + "\n"
    return out


# --------------------------------------------------------------------------- #
# Kubernetes
# --------------------------------------------------------------------------- #
def probe(p: dict, kind: str) -> dict:
    out = {"httpGet": {"path": p["path"], "port": p["port"]}}
    for src, dst in (("initial_delay", "initialDelaySeconds"),
                     ("period", "periodSeconds"),
                     ("failure_threshold", "failureThreshold")):
        if src in p:
            out[dst] = p[src]
    return out


def gen_k8s(spec: dict) -> dict[str, str]:
    meta, out = spec["meta"], {}
    ns, acct, region = meta["namespace"], meta["account_id"], meta["region"]
    ecr = f"{acct}.dkr.ecr.{region}.amazonaws.com"

    for name, s in spec["services"].items():
        pod = {
            "serviceAccountName": name,
            "containers": [{
                "name": name,
                "image": f"{ecr}/{s['image_repo']}:PLACEHOLDER_TAG",
                "ports": [{"containerPort": s["probes"]["readiness"]["port"]}],
                "resources": {k: {kk: str(vv) for kk, vv in v.items()}
                              for k, v in s["resources"].items()},
                "envFrom": [{"configMapRef": {"name": f"{name}-config"}}],
            }],
        }
        c = pod["containers"][0]
        for kind in ("startup", "readiness", "liveness"):
            if kind in s["probes"]:
                c[f"{kind}Probe"] = probe(s["probes"][kind], kind)
        if s.get("gpu"):
            pod["nodeSelector"] = s["gpu"]["node_selector"]
            pod["tolerations"] = [s["gpu"]["toleration"]]
        if s.get("init_container"):
            ic = spec["init_containers"][s["init_container"]]
            pod["initContainers"] = [{
                "name": s["init_container"],
                "image": f"{ecr}/{ic['image_repo']}:PLACEHOLDER_TAG",
                "resources": {k: {kk: str(vv) for kk, vv in v.items()}
                              for k, v in ic["resources"].items()},
                "envFrom": [{"configMapRef": {"name": f"{name}-config"}}],
                "volumeMounts": [{"name": "model", "mountPath": "/models"}],
            }]
            pod["volumes"] = [{"name": "model", "emptyDir": {"sizeLimit": "20Gi"}}]
            c["volumeMounts"] = [{"name": "model", "mountPath": "/models"}]

        docs = [
            {"apiVersion": "v1", "kind": "ServiceAccount",
             "metadata": {"name": name, "namespace": ns}},
            {"apiVersion": "apps/v1", "kind": "Deployment",
             "metadata": {"name": name, "namespace": ns},
             "spec": {"replicas": s["replicas"]["min"],
                      "selector": {"matchLabels": {"app": name}},
                      "template": {"metadata": {"labels": {"app": name}}, "spec": pod}}},
            {"apiVersion": "v1", "kind": "Service",
             "metadata": {"name": name, "namespace": ns},
             "spec": {"type": "ClusterIP", "selector": {"app": name},
                      "ports": [{"port": s["probes"]["readiness"]["port"],
                                 "targetPort": s["probes"]["readiness"]["port"]}]}},
        ]
        if s.get("hpa"):
            docs.append({
                "apiVersion": "autoscaling/v2", "kind": "HorizontalPodAutoscaler",
                "metadata": {"name": name, "namespace": ns},
                "spec": {"scaleTargetRef": {"apiVersion": "apps/v1",
                                            "kind": "Deployment", "name": name},
                         "minReplicas": s["replicas"]["min"],
                         "maxReplicas": s["replicas"]["max"],
                         "metrics": [{"type": "Resource", "resource": {
                             "name": s["hpa"]["metric"],
                             "target": {"type": "Utilization",
                                        "averageUtilization": s["hpa"]["target_utilization"]}}}]}})
        out[f"{name}.yaml"] = BANNER + yaml.dump_all(docs, sort_keys=False, width=100)
    return out


# --------------------------------------------------------------------------- #
def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any generated file is missing or stale")
    args = ap.parse_args()

    spec = yaml.safe_load((ROOT / "services.yaml").read_text())
    files = {IAM_DIR / k: v for k, v in gen_iam(spec).items()}
    files |= {K8S_DIR / k: v for k, v in gen_k8s(spec).items()}

    stale = []
    for path, content in files.items():
        if not path.exists() or path.read_text() != content:
            stale.append(path)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)

    if args.check:
        if stale:
            print("STALE — run platform/generate.py and commit:", file=sys.stderr)
            for p in stale:
                print(f"  {p.relative_to(ROOT.parent)}", file=sys.stderr)
            return 1
        print(f"generated output current ({len(files)} files)")
        return 0

    for p in sorted(files):
        print(f"  wrote {p.relative_to(ROOT.parent)}")
    print(f"\n{len(files)} files from services.yaml")
    return 0


if __name__ == "__main__":
    sys.exit(main())
