#!/usr/bin/env python3
"""Generate registry/languages/*.yaml from registry/sources.yaml.

Hand-writing 15 near-identical language files guarantees inconsistency. The
capability profile and licence status are DERIVED from the verified dataset
matrix, so a language cannot claim a capability no dataset provides.

    python scripts/generate_languages.py [--check]
"""
from __future__ import annotations
import argparse, hashlib, sys
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "registry" / "sources.yaml"
OUT = ROOT / "registry" / "languages"
GATES = ROOT / "registry" / "gates"
DECODE_APPROVALS = ROOT / "registry" / "decode-approvals" / "v1.yaml"

BANNER = ("# GENERATED by scripts/generate_languages.py from registry/sources.yaml\n"
          "# Edit sources.yaml, then regenerate. Do not hand-edit.\n")


def licence_for(ref: str, ds: dict) -> str:
    """dataset or dataset/provider -> commercial status."""
    if "/" in ref:
        name, prov = ref.split("/", 1)
        return ds[name]["providers"][prov]["commercial"]
    return ds[ref]["commercial"]


def decode_strategy_for(alias: str, approvals: dict) -> dict:
    """Resolve generated decode state from a separate versioned authority.

    Historical provisional evidence may be preserved exactly, but it is not a
    promotion approval. A future `approved_configuration` is accepted only
    when the source carries every provenance field required by B5.
    """
    pending = {
        "mode": "pending_experiment",
        "chosen_by_run": None,
        "frozen_eval": None,
        "candidates_compared": ["auto", "learned"],
    }
    entry = (approvals.get("languages") or {}).get(alias)
    if not entry:
        return pending
    if entry.get("promotion_state") not in {
            "PASS", "FAIL", "NOT_EVALUATED", "DEFERRED", "NOT_APPLICABLE"}:
        raise ValueError(f"{alias}: malformed decode promotion_state")
    if "historical_provisional_configuration" in entry:
        if entry["promotion_state"] == "PASS":
            raise ValueError(
                f"{alias}: provisional decode evidence cannot be promotion PASS")
        return entry["historical_provisional_configuration"]
    approved = entry.get("approved_configuration")
    if not approved:
        return pending
    required = {
        "mode", "prompt_tokens", "token_configuration", "search",
        "token_cap", "normalization", "frozen_eval", "chosen_by_run",
        "artifact_provenance", "code_provenance", "container_provenance",
    }
    missing = sorted(required - set(approved))
    if entry.get("promotion_state") != "PASS" or missing:
        raise ValueError(
            f"{alias}: decode approval is incomplete; missing {missing}")
    # The generated serving registry retains its compact contract. The full
    # immutable configuration remains in this approval source and is bound by
    # the signed promotion manifest.
    return {
        "mode": approved["mode"],
        "chosen_by_run": approved["chosen_by_run"],
        "frozen_eval": approved["frozen_eval"],
        "candidates_compared": approved.get("candidates_compared", []),
        "provisional": False,
    }


def scope_for(alias: str, current: dict) -> dict:
    """Resolve generated current-scope metadata from the versioned source."""
    active_training = set(current["active_training"])
    active_validation = set(current["active_validation"])
    deferred = set(current["deferred"])
    inactive = set(current["inactive_not_evaluated"])
    not_applicable = set(current["promotion_not_applicable"])
    if alias in deferred:
        training_state = validation_state = promotion_state = "DEFERRED"
    elif alias in inactive:
        training_state = validation_state = "INACTIVE"
        promotion_state = "NOT_EVALUATED"
    elif alias in not_applicable:
        training_state = validation_state = "NOT_APPLICABLE"
        promotion_state = "NOT_APPLICABLE"
    else:
        training_state = "ACTIVE" if alias in active_training else "INACTIVE"
        validation_state = "ACTIVE" if alias in active_validation else "INACTIVE"
        promotion_state = "NOT_EVALUATED"
    return {
        "decision_ref": current["decision_ref"],
        "decision_sha256": current["decision_sha256"],
        "training_state": training_state,
        "validation_state": validation_state,
        "promotion_state": promotion_state,
    }


def build(alias: str, e: dict, ds: dict, approvals: dict,
          current_scope: dict) -> dict:
    asr_srcs, tts_srcs = e.get("asr", []), e.get("tts", [])
    all_srcs = sorted(set(asr_srcs) | set(tts_srcs))
    lic = {s: licence_for(s, ds) for s in all_srcs}

    doc = {
        "alias": alias,
        "iso_code": e["iso"],
        "display_name": e.get("name", alias.title()),
        "status": "declared",
        "b4_b5_scope": scope_for(alias, current_scope),
        "capabilities": {
            "asr": {"available": bool(asr_srcs), "sources": asr_srcs},
            "tts": {"available": bool(tts_srcs), "sources": tts_srcs},
        },
        "asr": {
            "artifact": None,
            "approved_version": None,
            "decode_strategy": decode_strategy_for(alias, approvals),
        },
        "llm": {"engine": "bedrock", "policy": f"{alias}-medzen-v1",
                "qwen_trigger_rounds_failed": 0},
        "tts": {"provider": "fish", "voice_id": None, "approved": False,
                "consent_record": None,
                "adaptation_seed": tts_srcs[0] if tts_srcs else None,
                "fallback_provider": None},
        "thresholds_ref": f"gates/{alias}-v1.yaml",
        "fallback_language": "english" if alias != "english" else None,
        "provenance": {"data_sources": all_srcs, "licence_status": lic},
    }
    if e.get("iso_review"):
        doc["iso_review"] = True
    notes = []
    if e.get("note"):
        notes.append(e["note"].strip())
    if not asr_srcs:
        notes.append("NO ASR DATA: this language can be spoken but not understood. "
                     "The platform must refuse transcription for it.")
    if not tts_srcs:
        notes.append("NO TTS TRAINING DATA: speech comes from a provider voice, "
                     "not a model trained on this language.")
    if notes:
        doc["provenance"]["notes"] = "\n".join(notes)
    return doc


def default_gate(alias: str, e: dict) -> str:
    tonal = alias in {"igbo", "yoruba", "akan", "ewe", "twi"}
    body = [f"inherits: _defaults.yaml", f"language: {alias}", "version: v1-initial"]
    if tonal:
        body += ["rationale: |",
                 "  Tonal language with diacritics. CER is the primary metric —",
                 "  WER punishes a single tone mark as a whole-word error. NFC-normalise",
                 "  before scoring; report diacritized AND tone-stripped.",
                 "overrides:", "  asr:", "    absolute_wer_max: 0.30",
                 "    absolute_cer_max: 0.10"]
    else:
        body += ["rationale: Platform defaults; revisit once a baseline exists.",
                 "overrides: {}"]
    return "\n".join(body) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(); ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    src = yaml.safe_load(SRC.read_text())
    ds, langs, scope = src["datasets"], src["languages"], src["scope"]
    current_scope = src.get("b4_b5_scope") or {}
    required_scope_fields = {
        "decision_ref", "decision_sha256", "active_training",
        "active_validation", "deferred", "inactive_not_evaluated",
        "promotion_not_applicable",
    }
    if set(current_scope) != required_scope_fields:
        raise SystemExit("REFUSING: b4_b5_scope fields are incomplete or unknown")
    decision_path = ROOT / current_scope["decision_ref"]
    try:
        decision_sha = hashlib.sha256(decision_path.read_bytes()).hexdigest()
    except OSError as exc:
        raise SystemExit(f"REFUSING: scope decision is unreadable: {exc}")
    if decision_sha != current_scope["decision_sha256"]:
        raise SystemExit("REFUSING: generated scope decision hash differs")
    scope_groups = []
    for field in (
            "active_training", "active_validation", "deferred",
            "inactive_not_evaluated", "promotion_not_applicable"):
        value = current_scope[field]
        if (not isinstance(value, list)
                or any(not isinstance(alias, str) or not alias for alias in value)
                or len(set(value)) != len(value)):
            raise SystemExit(f"REFUSING: b4_b5_scope {field} is malformed")
        if field not in {"active_training", "active_validation"}:
            scope_groups.append(set(value))
    if current_scope["active_training"] or current_scope["active_validation"]:
        raise SystemExit("REFUSING: current active training/validation is not empty")
    flattened: set[str] = set()
    for group in scope_groups:
        if flattened & group:
            raise SystemExit("REFUSING: b4_b5_scope disposition groups overlap")
        flattened |= group
    if flattened != set(scope):
        raise SystemExit("REFUSING: b4_b5_scope does not cover registry scope")
    approvals = yaml.safe_load(DECODE_APPROVALS.read_text()) or {}
    if approvals.get("version") != "decode-approval-v1":
        raise SystemExit("REFUSING: unknown decode approval source version")

    files: dict[Path, str] = {}
    for alias in scope:
        if alias not in langs:
            print(f"FAIL scope names '{alias}' which is not in languages", file=sys.stderr)
            return 1
        files[OUT / f"{alias}.yaml"] = BANNER + yaml.dump(
            build(alias, langs[alias], ds, approvals, current_scope), sort_keys=False,
            allow_unicode=True, width=88)
        g = GATES / f"{alias}-v1.yaml"
        if not g.exists() or args_regen(g):
            files[g] = default_gate(alias, langs[alias])

    # PRESERVE EARNED STATE. status, decode_strategy, tts approval and consent
    # are results of experiments and reviews, not facts derivable from
    # sources.yaml. Regenerating must never silently discard them.
    import copy
    PRESERVE = [("status",), ("tts", "approved"), ("tts", "consent_record"),
                ("tts", "voice_id"), ("llm", "engine")]
    for path, content in list(files.items()):
        if path.parent != OUT or not path.exists():
            continue
        prev = yaml.safe_load(path.read_text()) or {}
        cur = yaml.safe_load(content)
        changed = False
        for keys in PRESERVE:
            src = prev
            for k in keys:
                if not isinstance(src, dict) or k not in src:
                    src = None; break
                src = src[k]
            if src is None:
                continue
            gen = cur
            for k in keys[:-1]:
                gen = gen.setdefault(k, {})
            if gen.get(keys[-1]) != src:
                gen[keys[-1]] = copy.deepcopy(src)
                changed = True
        if changed:
            files[path] = BANNER + yaml.dump(cur, sort_keys=False,
                                             allow_unicode=True, width=88)

    stale = [p for p, c in files.items() if not p.exists() or p.read_text() != c]
    if a.check:
        if stale:
            print("STALE — run scripts/generate_languages.py:", file=sys.stderr)
            for p in stale: print(f"  {p.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print(f"languages current ({len(files)} files)"); return 0

    # remove languages no longer in scope — but NEVER the hand-authored
    # data_only declarations: they are the A4 rung below 'declared', owned by
    # the data branch, invisible to sources.yaml by design. Deleting them
    # here destroyed evaluation-language records (idempotency failure caught
    # by test_b2_ingest) and the same preserve-earned-state rule that guards
    # status/tts/consent applies to their very existence.
    for f in OUT.glob("*.yaml"):
        if f.stem in scope:
            continue
        try:
            existing = yaml.safe_load(f.read_text())
        except yaml.YAMLError:
            existing = None
        if isinstance(existing, dict) and existing.get("status") == "data_only":
            continue
        f.unlink(); print(f"  removed {f.relative_to(ROOT)} (out of scope)")
    for p, c in files.items():
        p.parent.mkdir(parents=True, exist_ok=True); p.write_text(c)
    print(f"  wrote {len(files)} files for {len(scope)} languages")
    return 0


def args_regen(g: Path) -> bool:
    """Never overwrite a hand-tuned gate file that has real overrides."""
    try:
        d = yaml.safe_load(g.read_text()) or {}
        return not d.get("overrides")
    except Exception:
        return True


if __name__ == "__main__":
    sys.exit(main())
