#!/usr/bin/env python3
"""Generate registry/languages/*.yaml from registry/sources.yaml.

Hand-writing 15 near-identical language files guarantees inconsistency. The
capability profile and licence status are DERIVED from the verified dataset
matrix, so a language cannot claim a capability no dataset provides.

    python scripts/generate_languages.py [--check]
"""
from __future__ import annotations
import argparse, sys
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "registry" / "sources.yaml"
OUT = ROOT / "registry" / "languages"
GATES = ROOT / "registry" / "gates"

BANNER = ("# GENERATED by scripts/generate_languages.py from registry/sources.yaml\n"
          "# Edit sources.yaml, then regenerate. Do not hand-edit.\n")


def licence_for(ref: str, ds: dict) -> str:
    """dataset or dataset/provider -> commercial status."""
    if "/" in ref:
        name, prov = ref.split("/", 1)
        return ds[name]["providers"][prov]["commercial"]
    return ds[ref]["commercial"]


def build(alias: str, e: dict, ds: dict) -> dict:
    asr_srcs, tts_srcs = e.get("asr", []), e.get("tts", [])
    all_srcs = sorted(set(asr_srcs) | set(tts_srcs))
    lic = {s: licence_for(s, ds) for s in all_srcs}

    doc = {
        "alias": alias,
        "iso_code": e["iso"],
        "display_name": e.get("name", alias.title()),
        "status": "declared",
        "capabilities": {
            "asr": {"available": bool(asr_srcs), "sources": asr_srcs},
            "tts": {"available": bool(tts_srcs), "sources": tts_srcs},
        },
        "asr": {
            "artifact": None,
            "approved_version": None,
            "decode_strategy": {
                "mode": "pending_experiment",
                "chosen_by_run": None,
                "frozen_eval": None,
                "candidates_compared": ["auto", "learned"],
            },
        },
        "llm": {"engine": "bedrock", "policy": f"{alias}-medzen-v1",
                "qwen_trigger_rounds_failed": 0},
        "tts": {"provider": "fish", "voice_id": None, "approved": False,
                "consent_record": None,
                "adaptation_seed": tts_srcs[0] if tts_srcs else None,
                "fallback_provider": None},
        "thresholds_ref": f"gates/{alias}-v1.yaml",
        "fallback_language": "english" if alias != "english" else None,
        "provenance": {"data_sources": all_srcs, "licence_status": lic},
    }
    if e.get("iso_review"):
        doc["iso_review"] = True
    notes = []
    if e.get("note"):
        notes.append(e["note"].strip())
    if not asr_srcs:
        notes.append("NO ASR DATA: this language can be spoken but not understood. "
                     "The platform must refuse transcription for it.")
    if not tts_srcs:
        notes.append("NO TTS TRAINING DATA: speech comes from a provider voice, "
                     "not a model trained on this language.")
    if notes:
        doc["provenance"]["notes"] = "\n".join(notes)
    return doc


def default_gate(alias: str, e: dict) -> str:
    tonal = alias in {"igbo", "yoruba", "akan", "ewe", "twi"}
    body = [f"inherits: _defaults.yaml", f"language: {alias}", "version: v1-initial"]
    if tonal:
        body += ["rationale: |",
                 "  Tonal language with diacritics. CER is the primary metric —",
                 "  WER punishes a single tone mark as a whole-word error. NFC-normalise",
                 "  before scoring; report diacritized AND tone-stripped.",
                 "overrides:", "  asr:", "    absolute_wer_max: 0.30",
                 "    absolute_cer_max: 0.10"]
    else:
        body += ["rationale: Platform defaults; revisit once a baseline exists.",
                 "overrides: {}"]
    return "\n".join(body) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(); ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    src = yaml.safe_load(SRC.read_text())
    ds, langs, scope = src["datasets"], src["languages"], src["scope"]

    files: dict[Path, str] = {}
    for alias in scope:
        if alias not in langs:
            print(f"FAIL scope names '{alias}' which is not in languages", file=sys.stderr)
            return 1
        files[OUT / f"{alias}.yaml"] = BANNER + yaml.dump(
            build(alias, langs[alias], ds), sort_keys=False, allow_unicode=True, width=88)
        g = GATES / f"{alias}-v1.yaml"
        if not g.exists() or args_regen(g):
            files[g] = default_gate(alias, langs[alias])

    # PRESERVE EARNED STATE. status, decode_strategy, tts approval and consent
    # are results of experiments and reviews, not facts derivable from
    # sources.yaml. Regenerating must never silently discard them.
    import copy
    PRESERVE = [("status",), ("asr", "decode_strategy"),
                ("tts", "approved"), ("tts", "consent_record"),
                ("tts", "voice_id"), ("llm", "engine")]
    for path, content in list(files.items()):
        if path.parent != OUT or not path.exists():
            continue
        prev = yaml.safe_load(path.read_text()) or {}
        cur = yaml.safe_load(content)
        changed = False
        for keys in PRESERVE:
            src = prev
            for k in keys:
                if not isinstance(src, dict) or k not in src:
                    src = None; break
                src = src[k]
            if src is None:
                continue
            gen = cur
            for k in keys[:-1]:
                gen = gen.setdefault(k, {})
            if gen.get(keys[-1]) != src:
                gen[keys[-1]] = copy.deepcopy(src)
                changed = True
        if changed:
            files[path] = BANNER + yaml.dump(cur, sort_keys=False,
                                             allow_unicode=True, width=88)

    stale = [p for p, c in files.items() if not p.exists() or p.read_text() != c]
    if a.check:
        if stale:
            print("STALE — run scripts/generate_languages.py:", file=sys.stderr)
            for p in stale: print(f"  {p.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print(f"languages current ({len(files)} files)"); return 0

    # remove languages no longer in scope
    for f in OUT.glob("*.yaml"):
        if f.stem not in scope:
            f.unlink(); print(f"  removed {f.relative_to(ROOT)} (out of scope)")
    for p, c in files.items():
        p.parent.mkdir(parents=True, exist_ok=True); p.write_text(c)
    print(f"  wrote {len(files)} files for {len(scope)} languages")
    return 0


def args_regen(g: Path) -> bool:
    """Never overwrite a hand-tuned gate file that has real overrides."""
    try:
        d = yaml.safe_load(g.read_text()) or {}
        return not d.get("overrides")
    except Exception:
        return True


if __name__ == "__main__":
    sys.exit(main())
