#!/usr/bin/env python3
"""Regenerate the three v2 contract files from the committed v2 schemas.

B6v2 round 6 (Codex): rounds 4-5 generated these files with inline
throwaway code — one landed syntactically invalid, another pinned a hash
that went stale when a later edit touched a schema. Regeneration is now
a COMMITTED, reviewable step: run this after ANY v2 schema change, then
update V2_DEPLOYED_CONTRACTS in the orchestrator registry with the
printed shas. tests/test_b6v2_contracts.py refuses drift in both
directions.
"""
from __future__ import annotations

import hashlib
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]

HEADER = (
    "# B6v2 REAL-PROVIDER service contract (Codex serving review rounds 4-6).\n"
    "# The v1 contract file stays byte-frozen with the closed synthetic proof;\n"
    "# THIS file is the reviewed identity v2 registry routes pin (contract_id +\n"
    "# sha256 of these exact bytes - the same discipline as the v1 routes).\n"
    "# GENERATED by scripts/generate_b6v2_contracts.py - run it after any v2\n"
    "# schema change; tests/test_b6v2_contracts.py refuses drift.\n"
    "# Policy: platform/contracts/b6v2-real-providers.yaml.\n"
)


def _sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _schema_map(*dirnames: str) -> dict[str, str]:
    out: dict[str, str] = {}
    for dirname in dirnames:
        for f in sorted(
            (ROOT / "platform/contracts/schemas" / dirname).glob("*.json")
        ):
            out[f"{dirname}/{f.name}"] = _sha(f)
    return out


def documents() -> dict[str, dict]:
    return {
        "speech-v2": {
            "contract_id": "MEDZEN-SPEECH-CONTRACT-2026-002",
            "version": "medzen.speech.v2",
            "covers": ["asr-runtime", "rag-index", "speech-orchestrator"],
            "asr_identity": (
                "omniasr_ctc_1b:<artifact_tree_sha256[:12]> — the version "
                "derives from the ONE tree digest over checkpoint+tokenizer "
                "(reported snapshot omniasr-nonprod:<sha256>)"),
            "language_identities": (
                "registry alias + wire iso code -> omnilingual id, canonical "
                "map: medzen_model_loader.languages_v2 (pinned to "
                "registry/languages and language-conditioning-v1.json by test)"),
            "rag": (
                "citations carry grounding_text (1..1200 chars, non-blank); "
                "the reply cites a validated non-empty SUBSET; the binding "
                "hashes the reply's own citations; grounding_sha256 is "
                "verified and propagated end to end"),
            "response_audio": (
                "default false - zero synthesis calls unless requested"),
            "schemas": _schema_map(
                "speech-v2", "orchestrator-file-v2", "orchestrator-stream-v2"),
        },
        "llm-v2": {
            "contract_id": "MEDZEN-LLM-CONTRACT-2026-002",
            "version": "medzen.speech.v2",
            "provider_identities": ["fake-bedrock-local-v1",
                                     "bedrock:<model-id>"],
            "grounding": (
                "blank or whitespace-only grounding REFUSES "
                "(BLANK_GROUNDING 422) before any provider call; "
                "grounding_sha256 covers the exact citation block bytes sent "
                "and returns whenever real grounding was hashed"),
            "citations": (
                "cited_document_ids must be a NON-EMPTY subset of supplied ids"),
            "schemas": _schema_map("llm-v2"),
        },
        "tts-v2": {
            "contract_id": "MEDZEN-TTS-CONTRACT-2026-002",
            "version": "medzen.speech.v2",
            "provider_identities": ["fake_fish", "fish", "text_only"],
            "identity_delivery_exclusivity": (
                "round 6: real fish REQUIRES https + audio/mpeg + fish:s* "
                "version; the synthetic proof REQUIRES medzen+local + "
                "synthetic media; text_only REQUIRES null audio — mixed "
                "combinations refuse at the schema"),
            "voice_governance": (
                "strict JSON booleans; approval requires consent_evidence; "
                "the per-voice Fish model travels with the request; registry "
                "failure FAILS CLOSED"),
            "model_version": (
                "fish:<voice-model> fills the tts slot on synthesis only"),
            "schemas": _schema_map("tts-v2"),
        },
    }


def main() -> int:
    for name, document in documents().items():
        path = ROOT / "platform/contracts" / f"{name}.yaml"
        body = HEADER + yaml.safe_dump(
            document, sort_keys=True, width=78, default_flow_style=False)
        path.write_text(body)
        yaml.safe_load(path.read_text())          # must parse
        print(name, _sha(path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
